# Generated by Django 3.2.9 on 2022-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
