# Generated by Django 3.2.9 on 2022-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbankaccount_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
