# Generated by Django 4.1.3 on 2022-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userbankaccount_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
