# Generated by Django 4.1.3 on 2022-11-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20221110_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='to_account_no',
            field=models.PositiveIntegerField(),
        ),
    ]
